#' Code lineage from agreement titles
#'
#' @param database A database from the many packages ecosystem.
#' @return A list of lineages that combines agreement area
#' and agreement action.
#' @importFrom purrr map
#' @examples
#' \donttest{
#' code_lineage(qEnviron::agreements)
#' }
#' @export
code_lineage <- function(database) {
  title <- unname(unlist(purrr::map(database, "Title")))
  entity <- code_entity(title)
  action <- code_actions(title)
  parties <- code_parties(title)
  lineage <- ifelse(is.na(entity), paste0(parties, "-", action), paste0(entity, "-", action))
  lineage
}

#' Code Agreement Entity
#'
#' @param title Treaty titles
#' @return The region of the agreement
#' @importFrom entity location_entity
#' @examples
#' \donttest{
#' title <- sample(manyenviron::agreements$IEADB$Title, 30)
#' code_entity(title)
#' }
#' @export
code_entity <- function(title) {
  # MAke sure necessary model is available (adapted from entity package)
  outcome <- "openNLPmodels.en" %in% list.files(.libPaths())
  if (!outcome) {
    utils::install.packages(
      "http://datacube.wu.ac.at/src/contrib/openNLPmodels.en_1.5-1.tar.gz",
      repos=NULL,
      type="source")
  }
  # Code entity
  out <- entity::location_entity(title)
  # Remove states
  parties <- paste(countrynames$c, collapse = "|")
  out <- gsub(parties, "", out, ignore.case = TRUE)
  out <- gsub("^c", "", out)
  out <- gsub("[^[:alnum:]]", " ", out)
  out <- stringr::str_squish(out)
  out <- gsub("NULL", NA_character_, out)
  out <- ifelse(grepl("^$", out), NA_character_, out)
  out
}

#' Code Actions from agreement titles
#'
#' @param title Treaty titles
#' @return The action taken from agreement title
#' @importFrom dplyr case_when
#' @examples
#' \donttest{
#' title <- sample(manyenviron::agreements$IEADB$Title, 30)
#' code_actions(title)
#' }
#' @export
code_actions <- function(title) {
  dplyr::case_when(
    grepl("biodiversity|species|habitat|ecosystems|biological diversity|genetic resources|biosphere",
          title, ignore.case = T) ~ "biodiversity",
    grepl("air|atmos|climate|outer space|ozone|emissions|coal", title, ignore.case = T) ~ "climate change",
    grepl("legal|organization|enforcement|policy|planning|institution|dispute|court|tribunal|law",
          title, ignore.case = T) ~ "management",
    grepl("energy|nuclear|oil|mining|gas|hydro|power", title, ignore.case = T) ~  "energy",
    grepl("agricultur|food|livestock|crop|irrigation|cattle|meat|farm|cultivate",
          title, ignore.case = T) ~  "agriculture",
    grepl("waste|pollut|noise|toxic|hazard", title, ignore.case = T) ~  "waste",
    grepl("culture|scien|techno|trade|research|exploration|navigation|data|information",
          title, ignore.case = T) ~  "research",
    grepl("weapon|military", title, ignore.case = T) ~  "military")
  ## We can also try to do this with tagging sentence properties
  # title <- head(qEnviron::agreements$IEADB$Title)
  # We need to remove predicted_words here
  # out <- data.frame(title)
  # out <- rowid_to_column(out, var = "id")
  # library(udpipe)
  # ud_model <- udpipe_download_model(language = "english")
  # ud_model <- udpipe_load_model(ud_model$file_model)
  # x <- udpipe_annotate(ud_model, x = out$title, doc_id = out$id)
  # x <- as.data.frame(x)
  # abc <- "VB"
  # stats <- dplyr::filter(x,grepl(pattern = "VB", x = xpos, ignore.case = T))
  # But there are no verbs...
}

#' Get links from treaty titles
#'
#' Treaties that modify, amend, or expand other treaties
#' usually specify so in the title.
#' We use the qIDs generated by `code_agreements()` and
#' `condense_agreements()` to return a data frame of treaty
#' links for a database.
#' @param database A Package database
#' @param dataset A Package dataset
#' @param treaty_type The type of treaties to be returned.
#' By default, all treaties are returned.
#' Other options include bilateral or multilateral treaties. 
#' @return A dataframe of agreements' qID and their linkages.
#' @importFrom purrr map map_chr
#' @examples
#' \donttest{
#' get_links(database = manyenviron::agreements)
#' get_links(database = manyenviron::agreements, treaty_type = "multilateral")
#' get_links(dataset = manyenviron::agreements$IEADB, treaty_type = "bilateral")
#' samples <- lapply(manyenviron::agreements,
#' function(x) x[x$Beg > "1991-12-31" & x$Beg < "1993-01-01", ])
#' migraph::gglineage(get_links(samples))
#' }
#' @export
get_links <- function(database, dataset, treaty_type = "all") {
  # Get qID
  if (!missing(database)) {
    qID <- unname(unlist(purrr::map(database, "qID_ref")))
  }
  if (!missing(dataset)) {
    qID <- dataset$qID_ref
  }
  usethis::ui_done("qID column in dataset automatically found")
  # Filter by links
  qID <- grep(":", qID, value = TRUE)
  # Filter by treaty_type
  if (treaty_type == "bilateral") {
    qID <- grep("-", qID, value = TRUE)
  }
  if (treaty_type == "multilateral") {
    qID <- grep("-", qID, value = TRUE, invert = TRUE)
  } 
  # Split qID
  link <- purrr::map_chr(strsplit(qID, ":"), 2)
  agreement <- purrr::map_chr(strsplit(qID, ":"), 1)
  # Return dataset
  out <- data.frame(agreement, link)
  out
}
