#' Get links from treaty titles
#'
#' Treaties that modify, amend, or expand other treaties
#' usually specify so in the title.
#' We use the qIDs generated by `code_agreements()` and
#' `condense_qID()` to return a data frame of treaty
#' links for a database.
#' @param database A Package database
#' @param dataset A Package dataset
#' @param treaty_type The type of treaties to be returned.
#' By default, all treaties are returned.
#' Other options include bilateral or multilateral treaties. 
#' @return A dataframe of agreements' qID and their linkages.
#' @examples
#' get_links(database = qEnviron::agreements)
#' get_links(database = qEnviron::agreements, treaty_type = "multilateral")
#' get_links(dataset = qEnviron::agreements$IEADB, treaty_type = "bilateral")
#' \dontrun{
#' samples <- lapply(qEnviron::agreements,
#' function(x) x[x$Beg > "1991-12-31" & x$Beg < "1993-01-01", ])
#' migraph::gglineage(get_links(samples))
#' }
#' @export
get_links <- function(database, dataset, treaty_type = "all") {
  # Get qID
  if (!missing(database)) {
    qID <- unname(unlist(purrr::map(database, "qID_ref")))
  }
  if (!missing(dataset)) {
    qID <- dataset$qID_ref
  }
  usethis::ui_done("qID column in dataset automatically found")
  # Filter by links
  qID <- grep(":", qID, value = TRUE)
  # Filter by treaty_type
  if (treaty_type == "bilateral") {
    qID <- grep("-", qID, value = TRUE)
  }
  if (treaty_type == "multilateral") {
    qID <- grep("-", qID, value = TRUE, invert = TRUE)
  } 
  # Split qID
  link <- purrr::map_chr(strsplit(qID, ":"), 2)
  agreement <- purrr::map_chr(strsplit(qID, ":"), 1)
  # Return dataset
  out <- data.frame(agreement, link)
  out
}
