#' Code lineage from agreement titles
#'
#' @param database A database from the many packages ecosystem.
#' @return A list of lineages that combines agreement area
#' and agreement action.
#' @importFrom purrr map
#' @examples
#' code_lineage(qEnviron::agreements)
#' @export
code_lineage <- function(database) {
  title <- unname(unlist(purrr::map(database, "Title")))
  lineage <- paste0(code_actions(title), "-", code_area(title))
  lineage
}

#' Code Agreement Area
#'
#' @param title Treaty titles
#' @param destination Do you want regions or continents
#' returned instead of location names?
#' By default NULL.
#' Options include continent and region.
#' @return The region of the agreement
#' @importFrom entity location_entity
#' @importFrom countrycode countrycode
#' @examples
#' title <- head(qEnviron::agreements$IEADB$Title)
#' code_area(title)
#' @export
code_area <- function(title, destination = NULL) {
  # Code was adopted from entity package on GitHub
  outcome <- "openNLPmodels.en" %in% list.files(.libPaths())
  if (!outcome) {
      utils::install.packages(
        "http://datacube.wu.ac.at/src/contrib/openNLPmodels.en_1.5-1.tar.gz",
        repos=NULL,
        type="source")
  }
  out <- entity::location_entity(title)
  if(!is.null(destination)) {
    if (destination == "continent") {
      out <- lapply(out, function(x) countrycode::countrycode(x, origin = "country.name",
                                                              destination = "continent"))
      }
    if (destination == "region") {
      out <- lapply(out, function(x) countrycode::countrycode(x, origin = "country.name",
                                                              destination = "region"))
    }
  }
  out
}

#' Code Actions from agreement titles
#'
#' @param title Treaty titles
#' @return The action taken from agreement title
#' @importFrom dplyr case_when
#' @examples
#' code_actions(qEnviron::agreements$IEADB$Title)
#' @export
code_actions <- function(title) {
  dplyr::case_when(
    # For environmental treaties
    grepl("biodiversity|species|habitat|ecosystems|biological diversity|genetic resources|biosphere",
          title, ignore.case = T) ~ "biodiversity",
    grepl("air|atmos|climate|outer space|ozone|emissions|coal", title, ignore.case = T) ~ "climate change",
    grepl("legal|organization|enforcement|policy|planning|institution|dispute|court|tribunal|law",
          title, ignore.case = T) ~ "management",
    grepl("energy|nuclear|oil|mining|gas|hydro|power", title, ignore.case = T) ~  "energy",
    grepl("agricultur|food|livestock|crop|irrigation|cattle|meat|farm|cultivate|poultry",
          title, ignore.case = T) ~  "agriculture",
    grepl("waste|pollut|noise|toxic|hazard", title, ignore.case = T) ~  "waste",
    grepl("culture|scien|techno|trade|research|exploration|navigation|data|information",
          title, ignore.case = T) ~  "research",
    grepl("weapon|military", title, ignore.case = T) ~  "military",
    grepl("fish|salmon|herring|tuna|aquaculture|mariculture|molluscs", title,
          ignore.case = T) ~  "fishing",
    grepl("mammal|fauna|dolphin|whale|gorilla|elephant|animal|cattle|sheep|swine|wildlife|bird", title,
          ignore.case = T) ~  "fauna protection",
    grepl("flora|plant|fruit|vegetable|seed", title, ignore.case = T) ~  "flora protection",
    grepl("forest|tree", title, ignore.case = T) ~  "forestry",
    grepl("land|soil|wetland|desert|erosion", title, ignore.case = T) ~  "land protection",
    grepl("water|freshwater|river|rhine|hydro|basin|drought", title, ignore.case = T) ~  "freshwater",
    grepl("ocean|sea|marine|maritime|coastal|eez|continental shelf|aquatic", title, ignore.case = T) ~  "marine resources exploitation",
    # For trade treaties
    grepl("finance|fund", title, ignore.case = T) ~  "finance",
    grepl("economic union|economic community|free trade|common market|economic partnership|economic cooperation", title, ignore.case = T) ~  "market integration",
    grepl("invest", title, ignore.case = T) ~  "investement",
    grepl("water|freshwater|river|rhine|hydro|basin|drought", title, ignore.case = T) ~  "freshwater",
    )
  ## We can also try to do this with tagging sentence properties
  # title <- head(qEnviron::agreements$IEADB$Title)
  # We need to remove predicted_words here
  # out <- data.frame(title)
  # out <- rowid_to_column(out, var = "id")
  # library(udpipe)
  # ud_model <- udpipe_download_model(language = "english")
  # ud_model <- udpipe_load_model(ud_model$file_model)
  # x <- udpipe_annotate(ud_model, x = out$title, doc_id = out$id)
  # x <- as.data.frame(x)
  # abc <- "VB"
  # stats <- dplyr::filter(x,grepl(pattern = "VB", x = xpos, ignore.case = T))
  # There are no verbs...
}

#' Get links from treaty titles
#'
#' Treaties that modify, amend, or expand other treaties
#' usually specify so in the title.
#' We use the qIDs generated by `code_agreements()` and
#' `condense_qID()` to return a data frame of treaty
#' links for a database.
#' @param database A Package database
#' @param dataset A Package dataset
#' @param treaty_type The type of treaties to be returned.
#' By default, all treaties are returned.
#' Other options include bilateral or multilateral treaties. 
#' @return A dataframe of agreements' qID and their linkages.
#' @importFrom purrr map map_chr
#' @examples
#' get_links(database = qEnviron::agreements)
#' get_links(database = qEnviron::agreements, treaty_type = "multilateral")
#' get_links(dataset = qEnviron::agreements$IEADB, treaty_type = "bilateral")
#' \dontrun{
#' samples <- lapply(qEnviron::agreements,
#' function(x) x[x$Beg > "1991-12-31" & x$Beg < "1993-01-01", ])
#' migraph::gglineage(get_links(samples))
#' }
#' @export
get_links <- function(database, dataset, treaty_type = "all") {
  # Get qID
  if (!missing(database)) {
    qID <- unname(unlist(purrr::map(database, "qID_ref")))
  }
  if (!missing(dataset)) {
    qID <- dataset$qID_ref
  }
  usethis::ui_done("qID column in dataset automatically found")
  # Filter by links
  qID <- grep(":", qID, value = TRUE)
  # Filter by treaty_type
  if (treaty_type == "bilateral") {
    qID <- grep("-", qID, value = TRUE)
  }
  if (treaty_type == "multilateral") {
    qID <- grep("-", qID, value = TRUE, invert = TRUE)
  } 
  # Split qID
  link <- purrr::map_chr(strsplit(qID, ":"), 2)
  agreement <- purrr::map_chr(strsplit(qID, ":"), 1)
  # Return dataset
  out <- data.frame(agreement, link)
  out
}
