#' Get links from treaty titles
#'
#' Treaties that modify, amend, or expand other treaties
#' usually specify so in the title.
#' We use the qIDs generated by `code_agreements()` and
#' `condense_qID()` to return a data frame of these for
#' for a dataset or a database.
#' @param database A qPackage database
#' @param dataset A qPackage dataset
#' @param treaty_type The type of treaties to be returned.
#' By default, all.
#' Other options include bilateral or multilateral. 
#' @return A dataframe of agreements' qID and their linkages.
#' @examples
#' get_links(database = qEnviron::agreements)
#' get_links(dataset = qEnviron::agreements$IEADB)
#' @export
get_links <- function(database = NULL, dataset = NULL, treaty_type = "all") {
  # Get qID
  if (!is.null(database)) {
    qID <- unlist(purrr::map(database, "qID_ref"))
  }
  if (!is.null(dataset)) {
    qID <- dataset$qID_ref
  }
  usethis::ui_done("qID column in dataset automatically found")
  # Filter by links
  qID <- grep(":", qID, value = TRUE)
  # Filter by treaty_type
  if (treaty_type == "bilateral") {
    qID <- grep("-", qID, value = TRUE)
  }
  if (treaty_type == "multilateral") {
    qID <- grep("-", qID, value = TRUE, invert = TRUE)
  } 
  # Split qID
  link <- purrr::map_chr(strsplit(qID, ":"), 2)
  agreement <- purrr::map_chr(strsplit(qID, ":"), 1)
  # Return dataset
  out <- data.frame(agreement, link)
  out
}
